In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('50_Startups.csv')
dataset.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,4].values

文字データを0,1のタグに変換する処理。
sklearnkitのOneHotEncoderを用いて処理

In [4]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:,3] = labelencoder_X.fit_transform(X[:,3])
onehotencoder = OneHotEncoder(categorical_features = [3])
X = onehotencoder.fit_transform(X).toarray()

第一列をゼロとするため、削除

In [5]:
X = X[:, 1:]

In [6]:
pd.DataFrame(X).head()

     0    1          2          3          4
0  0.0  1.0  165349.20  136897.80  471784.10
1  0.0  0.0  162597.70  151377.59  443898.53
2  1.0  0.0  153441.51  101145.55  407934.54
3  0.0  1.0  144372.41  118671.85  383199.62
4  1.0  0.0  142107.34   91391.77  366168.42

In [7]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

/Users/yugi/.pyenv/versions/anaconda-4.0.0/envs/py36/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [8]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

In [9]:
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [10]:
y_pred = regressor.predict(X_test)

In [13]:
pd.DataFrame(np.c_[y_pred, y_test])

               0          1
0  103015.201598  103282.38
1  132582.277608  144259.40
2  132447.738452  146121.95
3   71976.098513   77798.83
4  178537.482211  191050.39
5  116161.242302  105008.31
6   67851.692097   81229.06
7   98791.733747   97483.56
8  113969.435330  110352.25
9  167921.065696  166187.94

In [12]:
import statsmodels.formula.api as sm

In [17]:
pd.DataFrame(X).head()

     0    1          2          3          4
0  0.0  1.0  165349.20  136897.80  471784.10
1  0.0  0.0  162597.70  151377.59  443898.53
2  1.0  0.0  153441.51  101145.55  407934.54
3  0.0  1.0  144372.41  118671.85  383199.62
4  1.0  0.0  142107.34   91391.77  366168.42

In [18]:
X = np.append(arr = np.ones((50,1)).astype(int), values = X, axis = 1)

In [19]:
pd.DataFrame(X).head()

     0    1    2          3          4          5
0  1.0  0.0  1.0  165349.20  136897.80  471784.10
1  1.0  0.0  0.0  162597.70  151377.59  443898.53
2  1.0  1.0  0.0  153441.51  101145.55  407934.54
3  1.0  0.0  1.0  144372.41  118671.85  383199.62
4  1.0  1.0  0.0  142107.34   91391.77  366168.42

In [23]:
X_opt = X[:, [0,1,2,3,4,5]]

In [24]:
pd.DataFrame(X_opt).head()

     0    1    2          3          4
0  1.0  0.0  1.0  165349.20  471784.10
1  1.0  0.0  0.0  162597.70  443898.53
2  1.0  1.0  0.0  153441.51  407934.54
3  1.0  0.0  1.0  144372.41  383199.62
4  1.0  1.0  0.0  142107.34  366168.42

In [26]:
regressorOLS = sm.OLS(endog=y, exog=X_opt).fit()

In [30]:
regressorOLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     215.8
Date:                Sat, 02 Jun 2018   Prob (F-statistic):           9.72e-29
Time:                        14:40:49   Log-Likelihood:                -525.53
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1071.
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.696e+04   3119.471     15.053      0.000    4.07e+04    5.32e+04
x1           140.7869   3341.599      0.042      0.967   -6589.538    6871.112
x2           -19.5234   3229.138     -0.006      0.995   -6523.340    6484.294
x3             0.7967      0.042     18.771      0.000       0.711       0.882
x4             0.0298      0.016      1.842      0.072      -0.003       0.062
==============================================================================
Omnibus:                       14.640   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.037
Skew:                          -0.938   Prob(JB):                     2.70e-05
Kurtosis:                       5.565   Cond. No.                     8.56e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 8.56e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [31]:
X_opt = X[:, [0,3,4,5]]
regressorOLS = sm.OLS(endog=y, exog=X_opt).fit()
regressorOLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     296.0
Date:                Sat, 02 Jun 2018   Prob (F-statistic):           4.53e-30
Time:                        14:42:11   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      46   BIC:                             1066.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.012e+04   6572.353      7.626      0.000    3.69e+04    6.34e+04
x1             0.8057      0.045     17.846      0.000       0.715       0.897
x2            -0.0268      0.051     -0.526      0.602      -0.130       0.076
x3             0.0272      0.016      1.655      0.105      -0.006       0.060
==============================================================================
Omnibus:                       14.838   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.442
Skew:                          -0.949   Prob(JB):                     2.21e-05
Kurtosis:                       5.586   Cond. No.                     1.40e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [32]:
X_opt = X[:, [0,3,5]]
regressorOLS = sm.OLS(endog=y, exog=X_opt).fit()
regressorOLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Sat, 02 Jun 2018   Prob (F-statistic):           2.16e-31
Time:                        14:45:50   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.698e+04   2689.933     17.464      0.000    4.16e+04    5.24e+04
x1             0.7966      0.041     19.266      0.000       0.713       0.880
x2             0.0299      0.016      1.927      0.060      -0.001       0.061
==============================================================================
Omnibus:                       14.677   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.161
Skew:                          -0.939   Prob(JB):                     2.54e-05
Kurtosis:                       5.575   Cond. No.                     5.32e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.32e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [33]:
X_opt = X[:, [0,3]]
regressorOLS = sm.OLS(endog=y, exog=X_opt).fit()
regressorOLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     849.8
Date:                Sat, 02 Jun 2018   Prob (F-statistic):           3.50e-32
Time:                        14:48:19   Log-Likelihood:                -527.44
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      48   BIC:                             1063.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.903e+04   2537.897     19.320      0.000    4.39e+04    5.41e+04
x1             0.8543      0.029     29.151      0.000       0.795       0.913
==============================================================================
Omnibus:                       13.727   Durbin-Watson:                   1.116
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               18.536
Skew:                          -0.911   Prob(JB):                     9.44e-05
Kurtosis:                       5.361   Cond. No.                     1.65e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.65e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [45]:
dataset.corr()

                 R&D Spend  Administration  Marketing Spend    Profit
R&D Spend         1.000000        0.241955         0.724248  0.972900
Administration    0.241955        1.000000        -0.032154  0.200717
Marketing Spend   0.724248       -0.032154         1.000000  0.747766
Profit            0.972900        0.200717         0.747766  1.000000

In [52]:
xdf = pd.DataFrame(X)
xdf[6] = pd.DataFrame(y)

In [53]:
xdf.head()

     0    1    2          3          4          5          6
0  1.0  0.0  1.0  165349.20  136897.80  471784.10  192261.83
1  1.0  0.0  0.0  162597.70  151377.59  443898.53  191792.06
2  1.0  1.0  0.0  153441.51  101145.55  407934.54  191050.39
3  1.0  0.0  1.0  144372.41  118671.85  383199.62  182901.99
4  1.0  1.0  0.0  142107.34   91391.77  366168.42  166187.94

In [55]:
import seaborn as sns
%matplotlib inline